#!/bin/bash
set -e
SRC=src/*.js
OUTFILE=bubblechart.min.js
echo "Checking JS"
for f in $SRC
do
  #echo "Checking $f"
  jshint $f --reporter src/buildtools/reporter.js
done

echo "Combining JS files"
DATE=`date +%s`
TMP=tmp_$DATE
TMPFILE=$TMP/tmp.js
mkdir $TMP
for f in $SRC
do
  #echo "Checking $f"
  touch $TMPFILE
  cat $f >> $TMPFILE
done

echo "Minifying JS files"
uglifyjs -o $OUTFILE $TMPFILE
rm -Rf $TMP